classPath: CATALOG_CLASS_PATH
entryPoints:
- de.fraunhofer.iem.secucheck.InternalFluentTQL.catalog.SQLInjection.CWE89.SimpleSQLInjection
- de.fraunhofer.iem.secucheck.InternalFluentTQL.catalog.CommandInjection.CWE77.CommandInjection
specPath: CATALOG_FLUENTTQL_SPEC_PATH
selectedSpecs:
- SimpleSQLi
asSpecFile: 'false'
solver: Boomerang3
isPostProcessResult: 'false'
