classPath: '/Volumes/Ranjith/Work/MagpieBridgeWork/MagpieForKotlin/spring-petclinic-kotlin/build/classes/kotlin/main'
entryPoints:
specPath: '/Volumes/Ranjith/Work/MagpieBridgeWork/MagpieForKotlin/secucheck-catalog/PetClinicSpecifications/target'
selectedSpecs:
asSpecFile: false
solver: "Boomerang3"
isPostProcessResult: false
