classPath: 'D:\Master\Fifth_sem\Thesis\SecuCheck-Kotlin\secucheck-catalog\kotlin-evaluation-project\target\classes'
entryPoints:
specPath: 'D:\Master\Fifth_sem\Thesis\SecuCheck-Kotlin\secucheck-catalog\kotlin-evaluation-project-specifications\target'
selectedSpecs:
asSpecFile: false
solver: "Boomerang3"
isPostProcessResult: false