classPath: 'D:\Master\Fifth_sem\Thesis\spring-evaluation-project\master-thesis-of-ranjith-krishnamurthy\spring-petclinic-kotlin\build\classes\kotlin\main'
entryPoints:
specPath: 'D:\Master\Fifth_sem\Thesis\SecuCheck-Kotlin\secucheck-catalog\PetClinicSpecifications\target'
selectedSpecs:
asSpecFile: false
solver: "Boomerang3"
isPostProcessResult: false