classPath: 'D:\Work\Secucheck\magpeibridge\v110\secucheck-magpiebridge\de.fraunhofer.iem.secucheck.InternalFluentTQL.catalog\target\classes'
entryPoints:
specPath: 'D:\Work\Secucheck\magpeibridge\v110\secucheck-magpiebridge\de.fraunhofer.iem.secucheck.InternalFluentTQL.catalogSpecifications\target'
selectedSpecs:
solver: "Boomerang3"