classPath: DEMO_PROJECT_CLASS_PATH
entryPoints:
- de.fraunhofer.iem.secucheck.todolist.TodoListApplication
- de.fraunhofer.iem.secucheck.todolist.configuration.SecurityConfiguration
- de.fraunhofer.iem.secucheck.todolist.configuration.WebMvcConfig
- de.fraunhofer.iem.secucheck.todolist.controllers.AdminController
- de.fraunhofer.iem.secucheck.todolist.controllers.DatabaseController
- de.fraunhofer.iem.secucheck.todolist.controllers.ErrorController
- de.fraunhofer.iem.secucheck.todolist.controllers.HomeController
- de.fraunhofer.iem.secucheck.todolist.controllers.LoginController
- de.fraunhofer.iem.secucheck.todolist.controllers.NewTaskController
- de.fraunhofer.iem.secucheck.todolist.controllers.PasswordController
- de.fraunhofer.iem.secucheck.todolist.controllers.TaskController
- de.fraunhofer.iem.secucheck.todolist.model.Role
- de.fraunhofer.iem.secucheck.todolist.model.Task
- de.fraunhofer.iem.secucheck.todolist.model.TaskList
- de.fraunhofer.iem.secucheck.todolist.model.User
- de.fraunhofer.iem.secucheck.todolist.model.UserList
- de.fraunhofer.iem.secucheck.todolist.repository.RoleRepository
- de.fraunhofer.iem.secucheck.todolist.repository.TaskRepository
- de.fraunhofer.iem.secucheck.todolist.repository.UserRepository
- de.fraunhofer.iem.secucheck.todolist.service.DirectoryStorageService
- de.fraunhofer.iem.secucheck.todolist.service.FileNotFoundException
- de.fraunhofer.iem.secucheck.todolist.service.FileSystemStorageService
- de.fraunhofer.iem.secucheck.todolist.service.StorageException
- de.fraunhofer.iem.secucheck.todolist.service.StorageProperties
- de.fraunhofer.iem.secucheck.todolist.service.UserService
- de.fraunhofer.iem.secucheck.todolist.utils.SecurityUtils
specPath: DEMO_PROJECT_FLUENTTQL_SPEC_PATH
selectedSpecs:
- CWE643_XpathInjection_TF1
- CWE601_OpenRedirect_TF1
- CWE79_CrossSiteScripting
- CWE22_PathTraversal
- CWE78_OsCommandInjection_TF2
- CWE20_ImproperInputValidation
asSpecFile: 'false'
solver: Boomerang3
isPostProcessResult: 'false'
