classPath: WEBGOAT_CLASS_PATH
entryPoints:
- org.owasp.webgoat.sql_injection.introduction.SqlInjectionLesson5b
- org.owasp.webgoat.sql_injection.advanced.SqlInjectionAdvanced
specPath: WEBGOAT_FLUENTTQL_SPEC_PATH
selectedSpecs:
- SQLInjectionLesson5b
asSpecFile: 'false'
solver: Boomerang3
isPostProcessResult: 'false'
